### ISSUE TITLE
Validity Check Fails During Installation

### ISSUE THREAD

**Issue by acxz** [ros-melodic-arch/ros-melodic-pluginlib#1]
When trying to install this package, the validity check fails and the package is not able to install.

**Comment by bionade24** [comment]
I'm currently at RobotCup GermanOpen, so you'll probably have to to wait until Tuesday.

**Comment by acxz** [comment]
Thank you for the response! Sure, I'll wait. Have fun at RobotCup!

**Comment by acxz** [comment]
Hey @bionade24, is there any update on this package?

**Comment by bionade24** [comment]
Solved in PR #3

**Comment by stangier** [comment]
Hey, I just wanted to install ROS melodic and got the same problem as @acxz in the first post.

**Comment by acxz** [comment]
I just went ahead and reinstalled this package and I am not having this issue, in fact the package successfully installs for me. There may be something else going on in your case @lstangier .

**Comment by stangier** [comment]
Yes you are right. The issue resolved itself when I build the package clean. Very strange.

**Comment by acxz** [comment]
Most likely you had the previous (erroneous) one downloaded which is why you had to build it clean.
