### ISSUE TITLE
Updating the AUR package

### ISSUE THREAD

**Issue by acxz** [ros-melodic-arch/ros-melodic-pluginlib#6]
The current state of this repo installs for me, however, the AUR package has not been reflected with the up to date changes from this repo. Can the AUR repo be updated?

**Comment by bionade24** [comment]
This issue should make patch invalid: https://github.com/ros-melodic-arch/ros-melodic-pluginlib/commit/955955e4530735dd3fa7242fb0ceace9e551c0b9
